name: As Far as I Can See
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.25374
title: A conversation with myself.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#adadad'
    - '#545454'
    - '#7d7d7d'
    - '#070707'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
