name: As Far as I Can See
favicon: null
layout_spectrum: 0.75125
typography_spectrum: 0.9256234818603843
title: A conversation with myself.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edd2b8'
    - '#030203'
    - '#633836'
    - '#a89279'
    - '#847769'
  brandStrength: 1
  lightness: 0.8926400956697762
  saturation: 0.6373961123172194
  rhythmicContrast: 0.9424318976234645
purpose: []
