title: A conversation with myself.
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.1322055
favicon: null
name: As Far as I Can See
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.1109023
  lightness: 0.1697995
  saturation: 0.476817
  rhythmicContrast: 0.6296992
  brandColors:
    - '#D2D6E4'
    - '#0E1313'
    - '#9EB1C0'
    - '#67727A'
    - '#2D3E58'
typography_spectrum: 0.4135338
